### ISSUE TITLE
TcpSocket's constructor should return false on failure

### ISSUE THREAD

**Issue by ziolek** [domnikl/statsd-php#35]
It would be helpful if I could determine whether  connection was established.

**Comment by domnikl** [comment]
I think that would be helpful, but there is a problem in the design of the lib as this was never intended. The connect is done lazily here: https://github.com/domnikl/statsd-php/blob/master/lib/Connection/InetSocket.php#L114 a return is not possible.
Maybe we could add a special Exception for the TCP Connection that is only thrown when exception handling was enabled in the TcpConnection class and otherwise fails quietly to keep it backwars compatible. Would that suit your needs?

**Comment by ziolek** [comment]
Thanks for answering!

It would be enough if `send()` method called from `TcpSocket` was able to throw `Exception` in case of connection failure.

**Comment by domnikl** [comment]
@ziolek what do you think of my solution in https://github.com/domnikl/statsd-php/pull/36?

**Comment by ziolek** [comment]
That's exectly what I was talking about.

**Comment by domnikl** [comment]
Great, I'll merge it then!
